### ISSUE TITLE
Are these identifiers deterministic?

### ISSUE THREAD

**Issue by andrewbaxter** [regiontog/gensym#6]
The description says it uses UUID - does that mean the type names change every time the file is built or builds on different systems will have different type names?

**Comment by regiontog** [comment]
They are random by implementation right now. So they do change from build to build yes. But the goal is just to be unique. There might be a way to get deterministic identifiers which would be good for reproducible builds. 

The way I was using this none of the code generated would be called/used at runtime so I think it would be stripped from the binary anyways. But I'm not sure what use-cases other users have for this library though.
